services:
  # App php-fpm service
  app:
    image: stanislavgeorgiev/phpbuilds:${PHP_VERSION}
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./config/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app
    depends_on:
      - nginx
      - redis
      - phpmyadmin
      - mysql
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/:/etc/nginx/templates/
    ports:
      - ${WEBSITE_PORT}:${NGINX_LISTEN_PORT}
    environment:
      - NGINX_ROOT=${NGINX_DIR}
      - NGINX_LISTEN_PORT=${NGINX_LISTEN_PORT}
      - DOMAIN=${DOMAIN}
    networks:
      - app
  redis:
    image: 'redis:alpine'
    container_name: ${APP_NAME}_redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_ROOT_USER}
      PMA_PASSWORD: ${DB_ROOT_PW}
    ports:
      - ${PORT_PHPMYADMIN}:80
    depends_on:
      - mysql
    networks:
      - app
  mysql:
    image: mysql:latest
    command: [ mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci ]
    container_name: ${APP_NAME}_database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql/
    networks:
      - app
#Volumes
volumes:
  database:
    driver: local
  redis:
    driver: local
networks:
  app:
    driver: bridge
